#!/usr/bin/env python3
# ══════════════════════════════════════════════════════════════════════════
#  viz_umap_2d.py
# ──────────────────────────────────────────────────────────────────────────
#  Evo-Buch Curriculum-Atlas — Static 2D UMAP Visualization
# ──────────────────────────────────────────────────────────────────────────
#
#  PURPOSE
#  -------
#  Produces publication-quality, static 2D scatter plots of the per-concept
#  UMAP projections generated by `bertopic_pipeline.py`. These serve as:
#    - A fast visual QA pass over the pipeline's output (catch degenerate
#      clusters, encoding bugs, empty concepts, etc. without opening the
#      web app).
#    - Print-ready / slide-ready figures for papers, talks, reports.
#    - A durable "ground truth" rendering that is independent of any
#      JavaScript/Plotly rendering quirks in the web app.
#
#  DATA SOURCE (IMPORTANT DESIGN CHOICE)
#  --------------------------------------
#  This script reads exclusively from the **already-exported, validated**
#  `data/<Concept>.json` files and `data/manifest.json` — the exact same
#  artifacts consumed by `curriculum_atlas.html`. It deliberately does NOT
#  re-read BERTopic pickles or raw UMAP .npy caches. This guarantees the
#  static plots and the interactive web app can never silently diverge
#  (e.g. due to a stale cache or a metadata-cleaning fix applied in one
#  path but not the other).
#
#  COLOR CONSISTENCY
#  ------------------
#  Subject/state colors are assigned deterministically (stable hashing +
#  golden-angle hue spacing) and cached to `data/color_maps.json`. This
#  means:
#    - The same subject always gets the same color across every concept's
#      plot, across re-runs, and across `viz_umap_3d.py`.
#    - `curriculum_atlas.html` can optionally fetch this same file to keep
#      its Plotly color-by-subject legend visually consistent with the
#      static figures.
#  Topic colors are concept-scoped (topics are concept-specific) but are
#  *also* derived deterministically from the same hashing scheme, seeded
#  with the concept name, so re-running the script never reshuffles colors.
#
#  OUTPUTS
#  -------
#    out/visualizations/2d/<Concept>/umap2d_<Concept>_<colorby>_<theme>.<ext>
#    out/visualizations/2d/_overview/overview_<colorby>_<theme>.<ext>
#    data/color_maps.json   (shared, cached deterministic color assignments)
#
#  USAGE
#  -----
#    python viz_umap_2d.py
#    python viz_umap_2d.py --concepts Evolution,Kultur --color-by topic
#    python viz_umap_2d.py --theme light --formats png,svg --point-size 10
#    python viz_umap_2d.py --no-overview --exclude-outliers
#
# ══════════════════════════════════════════════════════════════════════════

from __future__ import annotations

import argparse
import colorsys
import hashlib
import json
import logging
import math
import sys
from pathlib import Path
from typing import Any, Optional

import numpy as np
import pandas as pd

try:
    import matplotlib
    matplotlib.use("Agg")  # Headless-safe backend; no display server required.
    import matplotlib.pyplot as plt
    from matplotlib.figure import Figure
    from matplotlib.axes import Axes
except ImportError as e:
    sys.exit(f"[FATAL] Missing dependency 'matplotlib': {e}. Run: pip install matplotlib")


# ══════════════════════════════════════════════════════════════════════════
#  CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════

# Keys the front-end's Color-By toggle supports (spec §3.3), plus two bonus
# diagnostic dimensions (state, grade_band) useful for analyst QA but not
# exposed in the web app's UI.
VALID_COLOR_BY = ["subject", "topic", "state", "grade_band"]

# Neutral color reserved for outliers / unknown / missing values across
# every color scheme, so "no signal" always reads the same way visually.
NEUTRAL_GRAY = "#8a8a8a"

# Golden-angle hue increment gives maximally-separated hues for arbitrarily
# many categories without needing to know the category count in advance —
# crucial since subject/topic counts vary per concept.
GOLDEN_ANGLE_DEG = 137.508

# Theme presets: (background, foreground/text, grid, spine)
THEMES: dict[str, dict[str, str]] = {
    "dark": {
        "bg": "#0f172a",      # slate-900 — matches the web app's dark theme
        "fg": "#e2e8f0",      # slate-200
        "grid": "#334155",    # slate-700
        "spine": "#475569",   # slate-600
    },
    "light": {
        "bg": "#fafafa",      # gray-50
        "fg": "#1e293b",      # slate-800
        "grid": "#e2e8f0",    # slate-200
        "spine": "#cbd5e1",   # slate-300
    },
}

FIGSIZE_CONCEPT = (9, 8)
FIGSIZE_OVERVIEW_CELL = (4.2, 4.0)
DEFAULT_DPI = 180
DEFAULT_POINT_SIZE = 7  # matplotlib scatter `s` (points^2), independent of the
                        # web app's px-radius slider — see README note below.


# ══════════════════════════════════════════════════════════════════════════
#  CLI
# ══════════════════════════════════════════════════════════════════════════

def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    base_dir = Path(__file__).resolve().parent
    p = argparse.ArgumentParser(
        description="Static 2D UMAP visualizations for the Curriculum Atlas.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--data-dir", type=Path, default=base_dir / "data",
                    help="Directory containing manifest.json and <Concept>.json.")
    p.add_argument("--out-dir", type=Path, default=base_dir / "out" / "visualizations" / "2d",
                    help="Output directory for rendered figures.")
    p.add_argument("--concepts", type=str, default=None,
                    help="Comma-separated subset of concepts to render. "
                         "Default: all concepts found in manifest.json.")
    p.add_argument("--color-by", type=str, default="subject,topic",
                    help=f"Comma-separated color dimensions to render. "
                         f"Choices: {VALID_COLOR_BY}")
    p.add_argument("--theme", type=str, default="both", choices=["dark", "light", "both"],
                    help="Which visual theme(s) to render.")
    p.add_argument("--formats", type=str, default="png",
                    help="Comma-separated output formats, e.g. 'png,svg,pdf'.")
    p.add_argument("--point-size", type=float, default=DEFAULT_POINT_SIZE,
                    help="Matplotlib marker size (points^2).")
    p.add_argument("--dpi", type=int, default=DEFAULT_DPI, help="Raster output resolution.")
    p.add_argument("--exclude-outliers", action="store_true",
                    help="Drop is_outlier==true records before plotting.")
    p.add_argument("--no-overview", dest="overview", action="store_false",
                    help="Skip generating the multi-concept overview grid.")
    p.add_argument("--force-color-maps", action="store_true",
                    help="Regenerate data/color_maps.json even if it already exists.")
    p.add_argument("--max-legend-items", type=int, default=18,
                    help="Cap legend entries per plot (long tails grouped as 'Weitere …').")
    p.add_argument("--log-level", default="INFO",
                    choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    return p.parse_args(argv)


def setup_logging(level: str) -> logging.Logger:
    logger = logging.getLogger("viz_umap_2d")
    logger.setLevel(getattr(logging, level))
    logger.handlers.clear()
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)-7s] %(message)s",
                                            datefmt="%H:%M:%S"))
    logger.addHandler(handler)
    return logger


# ══════════════════════════════════════════════════════════════════════════
#  DATA LOADING (reads the canonical, already-validated web-app JSON)
# ══════════════════════════════════════════════════════════════════════════

def load_manifest(data_dir: Path, log: logging.Logger) -> dict[str, Any]:
    """Load data/manifest.json, produced by bertopic_pipeline.py.

    The manifest gives us the authoritative concept list and per-concept
    summary stats without needing to open every JSON file up front.
    """
    manifest_path = data_dir / "manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(
            f"manifest.json not found at {manifest_path}. "
            f"Run bertopic_pipeline.py first to generate the data/ directory."
        )
    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)
    log.info(f"Loaded manifest: {len(manifest.get('concepts', {}))} concept(s), "
             f"generated {manifest.get('generated_at', '?')}.")
    return manifest


def load_concept_frame(
    data_dir: Path, concept: str, log: logging.Logger,
) -> Optional[pd.DataFrame]:
    """Load and validate data/<Concept>.json into a flat, plot-ready DataFrame.

    Returns None (with a logged warning) if the file is missing, empty, or
    fails schema validation — callers should skip the concept gracefully
    rather than crashing the whole batch run.
    """
    path = data_dir / f"{concept}.json"
    if not path.exists():
        log.warning(f"[{concept}] No data file at {path} — skipping.")
        return None

    with open(path, "r", encoding="utf-8") as f:
        records = json.load(f)

    if not records:
        log.warning(f"[{concept}] Data file is empty — skipping.")
        return None

    required_keys = {"id", "state", "subject", "grade_band", "topic",
                      "is_outlier", "umap_2d", "excerpt"}
    missing_keys = required_keys - set(records[0].keys())
    if missing_keys:
        log.error(f"[{concept}] Record schema missing key(s) {missing_keys} — skipping.")
        return None

    df = pd.DataFrame.from_records(records)
    # umap_2d is stored as a [x, y] list per record; explode into flat columns
    # for straightforward vectorised plotting.
    xy = np.array(df["umap_2d"].tolist(), dtype=float)
    df["x"], df["y"] = xy[:, 0], xy[:, 1]
    df["is_outlier"] = df["is_outlier"].astype(bool)

    log.info(f"[{concept}] Loaded {len(df):,} records "
             f"({df['is_outlier'].sum()} outlier).")
    return df


# ══════════════════════════════════════════════════════════════════════════
#  DETERMINISTIC COLOR ASSIGNMENT
# ══════════════════════════════════════════════════════════════════════════

def _stable_hash_unit(label: str, salt: str = "") -> float:
    """Map an arbitrary string to a stable float in [0, 1) via MD5.

    Using a cryptographic hash (rather than Python's salted built-in hash())
    guarantees the same label always maps to the same value across
    processes and across machines — essential for reproducible color
    assignment when this script is re-run (or run in CI).
    """
    digest = hashlib.md5(f"{salt}::{label}".encode("utf-8")).hexdigest()
    # Use the first 8 hex chars (32 bits) as the source of randomness.
    return int(digest[:8], 16) / 0xFFFFFFFF


def deterministic_palette(labels: list[str], salt: str = "") -> dict[str, str]:
    """Assign each label a stable, well-separated hex color.

    Strategy: sort labels alphabetically first (so insertion order never
    matters), then walk the golden angle around the hue circle, starting
    from a per-label hash-derived offset so the *sequence* of hues is
    reproducible but not trivially "first label = red, second = orange…"
    (which would look monotonous across many concepts sharing a palette).

    Saturation/lightness are fixed for visual consistency; only hue varies.
    """
    sorted_labels = sorted(labels)
    if not sorted_labels:
        return {}

    # Deterministic starting hue derived from the salt (e.g. concept name),
    # so different concepts' topic palettes don't all start at the same hue.
    start_hue = _stable_hash_unit(salt or "palette", "start") * 360.0

    palette: dict[str, str] = {}
    for i, label in enumerate(sorted_labels):
        hue = (start_hue + i * GOLDEN_ANGLE_DEG) % 360.0 / 360.0
        # Slight deterministic jitter in saturation/lightness (derived from
        # the label itself) avoids a too-uniform, artificial look while
        # remaining perfectly reproducible.
        jitter = _stable_hash_unit(label, salt)
        saturation = 0.55 + 0.15 * jitter
        lightness = 0.52 + 0.10 * (1 - jitter)
        r, g, b = colorsys.hls_to_rgb(hue, lightness, saturation)
        palette[label] = f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"
    return palette


def load_or_build_color_maps(
    manifest: dict[str, Any], data_dir: Path, log: logging.Logger, force: bool = False,
) -> dict[str, Any]:
    """Load `data/color_maps.json` if present, else build it from the
    manifest's aggregated subject/state counts and persist it.

    The color map file has the structure:
      {
        "subject": { "<Subject>": "#rrggbb", ... },
        "state":   { "<State>":   "#rrggbb", ... },
        "outlier_color": "#8a8a8a"
      }
    Topic colors are intentionally NOT stored here (they are concept-scoped
    and computed on the fly per plot) — only globally-shared dimensions are
    cached.
    """
    path = data_dir / "color_maps.json"
    if path.exists() and not force:
        with open(path, "r", encoding="utf-8") as f:
            color_maps = json.load(f)
        log.info(f"Loaded cached color maps from {path}.")
        return color_maps

    log.info("Building global color maps for 'subject' and 'state' …")
    all_subjects: set[str] = set()
    all_states: set[str] = set()
    for frag in manifest.get("concepts", {}).values():
        all_subjects.update(frag.get("subjects", {}).keys())
        all_states.update(frag.get("states", {}).keys())

    color_maps = {
        "subject": deterministic_palette(sorted(all_subjects), salt="subject"),
        "state": deterministic_palette(sorted(all_states), salt="state"),
        "outlier_color": NEUTRAL_GRAY,
    }

    data_dir.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(color_maps, f, ensure_ascii=False, indent=2)
    log.info(f"Wrote {len(all_subjects)} subject color(s), {len(all_states)} state "
             f"color(s) -> {path}")
    return color_maps


def resolve_color_map(
    df: pd.DataFrame, color_by: str, color_maps: dict[str, Any], concept: str,
) -> dict[str, str]:
    """Return the label -> hex-color mapping to use for a given plot.

    - 'subject' / 'state': pulled from the shared, cross-concept color_maps
      dict (falls back to on-the-fly generation for any label not present,
      e.g. if new data was added after color_maps.json was cached).
    - 'topic' / 'grade_band': generated fresh, scoped to this concept, since
      topic IDs/labels are not comparable across concepts.
    """
    labels = sorted(df[color_by].dropna().unique().tolist())
    if color_by in ("subject", "state"):
        cached = color_maps.get(color_by, {})
        missing = [l for l in labels if l not in cached]
        if missing:
            cached = {**cached, **deterministic_palette(missing, salt=color_by)}
        return {l: cached.get(l, NEUTRAL_GRAY) for l in labels}
    # topic / grade_band: concept-scoped deterministic palette
    return deterministic_palette(labels, salt=f"{concept}:{color_by}")


# ══════════════════════════════════════════════════════════════════════════
#  PLOT STYLING HELPERS
# ══════════════════════════════════════════════════════════════════════════

def new_themed_axes(figsize: tuple[float, float], theme: str) -> tuple[Figure, Axes]:
    """Create a Figure/Axes pair pre-styled for the given theme."""
    t = THEMES[theme]
    fig, ax = plt.subplots(figsize=figsize, facecolor=t["bg"])
    ax.set_facecolor(t["bg"])
    ax.tick_params(colors=t["fg"], labelsize=8)
    ax.xaxis.label.set_color(t["fg"])
    ax.yaxis.label.set_color(t["fg"])
    ax.title.set_color(t["fg"])
    for spine in ax.spines.values():
        spine.set_edgecolor(t["spine"])
    ax.grid(color=t["grid"], linestyle="--", linewidth=0.5, alpha=0.6)
    return fig, ax


def cap_legend_categories(
    counts: pd.Series, max_items: int,
) -> tuple[list[str], bool]:
    """Return the top-`max_items` categories by frequency, plus a flag
    indicating whether a "Weitere …" (Other) bucket was needed.

    Prevents legends from overflowing off-canvas for concepts with e.g.
    40+ distinct subjects — the long tail is drawn but not individually
    labelled, keeping the figure legible.
    """
    if len(counts) <= max_items:
        return counts.index.tolist(), False
    return counts.sort_values(ascending=False).head(max_items).index.tolist(), True


# ══════════════════════════════════════════════════════════════════════════
#  PER-CONCEPT PLOT
# ══════════════════════════════════════════════════════════════════════════

def plot_concept_2d(
    df: pd.DataFrame,
    concept: str,
    color_by: str,
    theme: str,
    color_maps: dict[str, Any],
    point_size: float,
    max_legend_items: int,
    include_outliers: bool,
    out_dir: Path,
    formats: list[str],
    dpi: int,
    log: logging.Logger,
) -> None:
    """Render a single themed, color-coded 2D UMAP scatter plot for one
    concept and save it in every requested format.
    """
    plot_df = df if include_outliers else df.loc[~df["is_outlier"]]
    if plot_df.empty:
        log.warning(f"[{concept}] No plottable rows for color_by={color_by} "
                    f"(include_outliers={include_outliers}) — skipping.")
        return

    t = THEMES[theme]
    color_map = resolve_color_map(plot_df, color_by, color_maps, concept)
    counts = plot_df[color_by].value_counts()
    shown_labels, has_overflow = cap_legend_categories(counts, max_legend_items)
    shown_set = set(shown_labels)

    fig, ax = new_themed_axes(FIGSIZE_CONCEPT, theme)

    # Draw largest-count categories first so rarer (often more interesting)
    # categories are layered on top and remain visible rather than buried.
    for label in counts.index:
        mask = plot_df[color_by] == label
        sub = plot_df.loc[mask]
        color = color_map.get(label, NEUTRAL_GRAY)
        legend_label = label if label in shown_set else None
        ax.scatter(
            sub["x"], sub["y"], s=point_size, c=color, alpha=0.78,
            linewidths=0, label=legend_label, rasterized=True,
        )

    if has_overflow:
        n_hidden = len(counts) - len(shown_labels)
        ax.scatter([], [], s=point_size, c=NEUTRAL_GRAY,
                   label=f"Weitere ({n_hidden}) …")

    legend = ax.legend(
        loc="upper left", bbox_to_anchor=(1.01, 1.0), fontsize=7.5,
        facecolor=t["bg"], edgecolor=t["spine"], labelcolor=t["fg"],
        title=color_by.replace("_", " ").title(), title_fontsize=8.5,
        borderaxespad=0.0, ncol=1, markerscale=1.6,
    )
    legend.get_frame().set_alpha(0.85)

    ax.set_title(f"{concept} — UMAP 2D  ·  eingefärbt nach {color_by}",
                 fontsize=13, pad=12)
    ax.set_xlabel("UMAP-1")
    ax.set_ylabel("UMAP-2")
    ax.set_aspect("auto")
    fig.tight_layout(rect=[0, 0, 0.82, 1])  # reserve space for the outside legend

    concept_dir = out_dir / concept
    concept_dir.mkdir(parents=True, exist_ok=True)
    for fmt in formats:
        out_path = concept_dir / f"umap2d_{concept}_{color_by}_{theme}.{fmt}"
        fig.savefig(out_path, dpi=dpi, facecolor=t["bg"], bbox_inches="tight")
        log.debug(f"  Saved {out_path}")
    plt.close(fig)
    log.info(f"[{concept}] Saved {color_by}/{theme} plot "
             f"({len(formats)} format(s)).")


# ══════════════════════════════════════════════════════════════════════════
#  MULTI-CONCEPT OVERVIEW GRID
# ══════════════════════════════════════════════════════════════════════════

def plot_overview_grid(
    frames: dict[str, pd.DataFrame],
    color_by: str,
    theme: str,
    color_maps: dict[str, Any],
    point_size: float,
    include_outliers: bool,
    out_dir: Path,
    formats: list[str],
    dpi: int,
    log: logging.Logger,
) -> None:
    """Render a single small-multiples figure: one mini-scatter per concept,
    arranged in a near-square grid, for a bird's-eye view of the entire
    Curriculum Atlas at once (useful for spotting concepts with degenerate
    or unusually small/sparse embeddings at a glance).
    """
    concepts = list(frames.keys())
    if not concepts:
        log.warning("No concept data available — skipping overview grid.")
        return

    n = len(concepts)
    n_cols = math.ceil(math.sqrt(n))
    n_rows = math.ceil(n / n_cols)
    t = THEMES[theme]

    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(FIGSIZE_OVERVIEW_CELL[0] * n_cols, FIGSIZE_OVERVIEW_CELL[1] * n_rows),
        facecolor=t["bg"], squeeze=False,
    )

    for idx, concept in enumerate(concepts):
        r, c = divmod(idx, n_cols)
        ax = axes[r][c]
        ax.set_facecolor(t["bg"])
        for spine in ax.spines.values():
            spine.set_edgecolor(t["spine"])
        ax.tick_params(colors=t["fg"], labelsize=6)

        df = frames[concept]
        plot_df = df if include_outliers else df.loc[~df["is_outlier"]]
        if plot_df.empty:
            ax.text(0.5, 0.5, "Keine Daten", ha="center", va="center",
                     color=t["fg"], fontsize=9, transform=ax.transAxes)
        else:
            color_map = resolve_color_map(plot_df, color_by, color_maps, concept)
            colors = plot_df[color_by].map(color_map).fillna(NEUTRAL_GRAY)
            ax.scatter(plot_df["x"], plot_df["y"], s=max(point_size * 0.5, 2),
                       c=colors, alpha=0.7, linewidths=0, rasterized=True)

        ax.set_title(concept, color=t["fg"], fontsize=10, pad=4)
        ax.set_xticks([])
        ax.set_yticks([])

    # Blank out any unused grid cells (n_rows * n_cols may exceed n concepts).
    for idx in range(n, n_rows * n_cols):
        r, c = divmod(idx, n_cols)
        axes[r][c].axis("off")

    fig.suptitle(f"Evo-Buch Curriculum-Atlas — Übersicht ({color_by})",
                 color=t["fg"], fontsize=16, y=1.0)
    fig.tight_layout(rect=[0, 0, 1, 0.98])

    overview_dir = out_dir / "_overview"
    overview_dir.mkdir(parents=True, exist_ok=True)
    for fmt in formats:
        out_path = overview_dir / f"overview_{color_by}_{theme}.{fmt}"
        fig.savefig(out_path, dpi=dpi, facecolor=t["bg"], bbox_inches="tight")
        log.info(f"Saved overview grid -> {out_path}")
    plt.close(fig)


# ══════════════════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════════════════

def main() -> None:
    args = parse_args()
    log = setup_logging(args.log_level)

    log.info("=" * 78)
    log.info("  Curriculum Atlas — Static 2D UMAP Visualizations")
    log.info("=" * 78)

    color_by_list = [c.strip() for c in args.color_by.split(",") if c.strip()]
    invalid = [c for c in color_by_list if c not in VALID_COLOR_BY]
    if invalid:
        sys.exit(f"[FATAL] Invalid --color-by value(s) {invalid}. "
                 f"Choices: {VALID_COLOR_BY}")

    themes = ["dark", "light"] if args.theme == "both" else [args.theme]
    formats = [f.strip().lstrip(".") for f in args.formats.split(",") if f.strip()]

    manifest = load_manifest(args.data_dir, log)
    available_concepts = list(manifest.get("concepts", {}).keys())

    if args.concepts:
        requested = [c.strip() for c in args.concepts.split(",") if c.strip()]
        concepts = [c for c in requested if c in available_concepts]
        skipped = set(requested) - set(concepts)
        if skipped:
            log.warning(f"Requested concept(s) not in manifest, skipping: {skipped}")
    else:
        concepts = manifest.get("concept_order", available_concepts)
        concepts = [c for c in concepts if c in available_concepts]

    log.info(f"Rendering {len(concepts)} concept(s) × {len(color_by_list)} color "
             f"scheme(s) × {len(themes)} theme(s) × {len(formats)} format(s).")

    color_maps = load_or_build_color_maps(manifest, args.data_dir, log,
                                           force=args.force_color_maps)

    # Load every requested concept's frame once, reused across all
    # color-by/theme/format combinations (and by the overview grid).
    frames: dict[str, pd.DataFrame] = {}
    for concept in concepts:
        df = load_concept_frame(args.data_dir, concept, log)
        if df is not None:
            frames[concept] = df

    for concept, df in frames.items():
        for color_by in color_by_list:
            if color_by not in df.columns:
                log.warning(f"[{concept}] Column '{color_by}' not present — skipping.")
                continue
            for theme in themes:
                plot_concept_2d(
                    df, concept, color_by, theme, color_maps,
                    args.point_size, args.max_legend_items,
                    include_outliers=not args.exclude_outliers,
                    out_dir=args.out_dir, formats=formats, dpi=args.dpi, log=log,
                )

    if args.overview:
        for color_by in color_by_list:
            if color_by == "topic":
                log.info("Skipping overview grid for 'topic' — topic IDs are "
                         "concept-scoped and not visually comparable across "
                         "concepts in a single shared figure.")
                continue
            for theme in themes:
                plot_overview_grid(
                    frames, color_by, theme, color_maps, args.point_size,
                    include_outliers=not args.exclude_outliers,
                    out_dir=args.out_dir, formats=formats, dpi=args.dpi, log=log,
                )

    log.info("=" * 78)
    log.info(f"DONE. Rendered {len(frames)}/{len(concepts)} concept(s) successfully.")
    log.info("=" * 78)


if __name__ == "__main__":
    main()
